CROSS = arm-uclinux-
CC = $(CROSS)gcc
AR = $(CROSS)ar
STRIP = $(CROSS)strip
LD = ldelf2flt

all:
	$(MAKE) -f All.mak all

clean: 
	$(MAKE) -f All.mak clean

gpl-clean: 
	$(MAKE) -f All.mak gpl-clean

install:
	$(MAKE) -f All.mak install
