GPL_LICENSE	= yes
INSTALL_DIR	= $(PROJ_INSTALL)/usr/local/bin
CFLAGS += -I$(PROJ_ROOT)/src/sysapps/apps/samba_3.06/include
LDFLAGS += -L$(PROJ_ROOT)/src/sysapps/apps/samba_3.06/bin -lsmbclient
include $(PROJ_CGI2)/makefiles/makefile_exe
