#
# Makefile for USB OTG Controller Driver
# framework and drivers
#

O_TARGET	:= OTG.o

obj-$(CONFIG_FARADAY_FOTG2XX)			+= FTC_FOTG2XX.o

export-objs :=			FTC_FOTG2XX.o  






include $(TOPDIR)/Rules.make



