h:
	@ln -sf ../../conf_sec.h .
	@ln -sf ../../model.h .
	@ln -sf ../../NTP/fntp.h .
	@ln -sf ../../../../kernel/linux/include/asm/arch/memconfig.h .
	@ln -sf ../../model_conf/model_conf.h .
	@ln -sf ../../model_conf/model_common_conf.h .
	
clean gpl-clean uninstall distclean:
	@rm -rf *.h

info:

all install:
