#
# pl1601 dedicated character device dirvers
#


O_TARGET := pl1061snd.o

obj-$(CONFIG_PL1061_NEW_AC97DEV) := pl_ac97.o
obj-$(CONFIG_PL1061_PT5701) := pl_pt5701.o
obj-m := $(O_TARGET)


include ${TOPDIR}/Rules.make
