#ifndef _COMMON_CONF_H_
#define _COMMON_CONF_H_

#define VIEWER_OCX_FILEVERSION		"2,0,0,37"
#define ALERT_OCX_FILEVERSION		"2,0,0,15"
#define FW_VERSION			"V1.1.2R06"
#define FW_EXTENSION_VERSION		"E00"	
#define COMPANY_NAME			"Cisco"

#define _FCS_RELEASE_VERSION_FORMAT_	0
#endif
