all install:
	install -D Cisco2300Viewer.cab $(PROJ_INSTALL)/usr/local/www/Cisco2300Viewer.cab
	install -D CiscoAlertCfg.cab $(PROJ_INSTALL)/usr/local/www/adm/CiscoAlertCfg.cab

clean h info distclean uninstall gpl-clean:
